### ISSUE TITLE
Update: Trials Rising

### ISSUE THREAD

**Issue by kylefmohr** [AreWeAntiCheatYet/AreWeAntiCheatYet#1755]
### Game title

Trials Rising

### Status of the game anti-cheat

🏃 Running

### Tinkering steps

Run [this patcher](https://github.com/kylefmohr/Trials-Rising-Steam-Deck-Patch) or manually edit the .exe [using the steps found here](https://www.pcgamingwiki.com/wiki/Trials_Rising#Disable_Easy_Anti-Cheat).

### Proof of mention

https://www.kylemohr.com/Trials-Rising-EasyAntiCheat-Bypass-Analysis

**Comment by Starz0r** [comment]
I think as much as I like to list this, I can't accept it on the grounds of it being a AC bypass. Those are notoriously unsafe since they pose the risk of an account ban, but also if the game is ever update, usually so does the bypass.

Genshin infamously had a similar bypass, but we've never mentioned it on the site, but alluded to there being workarounds. These days you don't need any workarounds to play that game, so it's listed as Running. We would prefer that if a game is "working", you don't need to modify or patch the binary to play the game, rather it works without any invasive steps.
